# Generated by Django 3.2.7 on 2021-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210922_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.SlugField(max_length=254),
        ),
    ]
